### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by mattiase**
Some minor corrections and improvements.

### CODE REVIEW

**Comment by phikal** [comment]
LGTM, I have no objections.

**Comment by mattiase** [comment]
Thank you!

**Comment by minad** [comment]
Thank you, Mattias! Please let me know if you think we should soon create a new minor release with these changes.

**Comment by mattiase** [comment]
I'd leave it until there are more substantial changes. These were just things I noticed in passing (using an experimental linter, as it happens).

**Comment by minad** [comment]
Okay, makes sense!

**Pull request merged**
